import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import toast from "react-hot-toast";
import { Plus } from "lucide-react";
import { api, unwrap } from "../lib/api";
import { Badge, Button, Field, Input, Modal, PageHeader, Select, Textarea, SkeletonRows, statusTone } from "../components/ui";

export default function Events() {
  const queryClient = useQueryClient();
  const [open, setOpen] = useState(false);
  const [view, setView] = useState("list");
  const { data: events = [], isLoading } = useQuery({ queryKey: ["events"], queryFn: () => api.get("/events").then(unwrap) });
  const create = useMutation({ mutationFn: (payload) => api.post("/events", payload).then(unwrap), onSuccess: () => { toast.success("Event saved"); setOpen(false); queryClient.invalidateQueries({ queryKey: ["events"] }); }, onError: (e) => toast.error(e.response?.data?.message || "Could not save event") });
  const register = useMutation({ mutationFn: (id) => api.post(`/events/${id}/register`).then(unwrap), onSuccess: () => { toast.success("Registered"); queryClient.invalidateQueries({ queryKey: ["events"] }); }, onError: (e) => toast.error(e.response?.data?.message || "Could not register") });

  return <div className="grid gap-6"><PageHeader title="Events" action={<Button onClick={() => setOpen(true)}><Plus className="h-4 w-4" /> Create Event</Button>}>Manage calendar, registrations, attendance, and hackathon-specific details.</PageHeader><div className="inline-flex w-fit rounded-md border border-slate-700 bg-slate-900 p-1"><button className={`rounded px-3 py-1.5 text-sm ${view === "list" ? "bg-sky-400 text-slate-950" : "text-slate-300"}`} onClick={() => setView("list")}>List</button><button className={`rounded px-3 py-1.5 text-sm ${view === "calendar" ? "bg-sky-400 text-slate-950" : "text-slate-300"}`} onClick={() => setView("calendar")}>Calendar</button></div>{isLoading ? <SkeletonRows /> : view === "list" ? <div className="grid gap-4">{events.map((event) => <article className="rounded-md border border-slate-800 bg-slate-900 p-5" key={event.id}><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-white">{event.name}</h3><Badge tone="blue">{event.type}</Badge><Badge tone={statusTone(event.status)}>{event.status}</Badge></div><p className="mt-2 text-sm text-slate-400">{event.description}</p><div className="mt-3 text-sm text-slate-300">{event.venue} • {new Date(event.startDate).toLocaleString()}</div>{event.type === "HACKATHON" && <div className="mt-3 grid gap-2 text-sm text-slate-400"><span>{event.teamFormation}</span><span>{event.prizeDetails}</span>{event.projectSubmission && <a href={event.projectSubmission} className="text-sky-300">Submission link</a>}</div>}</div><div className="flex items-center gap-2"><Badge tone="slate">{event.participants.length}/{event.maxParticipants || "∞"}</Badge><Button variant="ghost" onClick={() => register.mutate(event.id)}>Register</Button></div></div></article>)}</div> : <Calendar events={events} />}{open && <EventModal onClose={() => setOpen(false)} onSubmit={(payload) => create.mutate(payload)} />}</div>;
}

function Calendar({ events }) {
  return <div className="grid gap-3 rounded-md border border-slate-800 bg-slate-900 p-4 sm:grid-cols-2 lg:grid-cols-3">{events.map((event) => <div className="rounded-md border border-slate-700 bg-slate-950 p-4" key={event.id}><div className="text-sm text-sky-300">{new Date(event.startDate).toLocaleDateString(undefined, { month: "short", day: "numeric" })}</div><div className="mt-2 font-medium text-white">{event.name}</div><div className="mt-1 text-sm text-slate-400">{event.venue}</div></div>)}</div>;
}

function EventModal({ onClose, onSubmit }) {
  const [form, setForm] = useState({ name: "", description: "", type: "MEETING", venue: "", startDate: "", endDate: "", status: "UPCOMING", registrationLink: "", bannerUrl: "", maxParticipants: 50, teamFormation: "", projectSubmission: "", prizeDetails: "" });
  return <Modal title="Create event" onClose={onClose}><form className="grid gap-4" onSubmit={(e) => { e.preventDefault(); onSubmit(form); }}><Field label="Name"><Input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><Field label="Description"><Textarea required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field><div className="grid gap-4 sm:grid-cols-3"><Field label="Type"><Select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option>HACKATHON</option><option>WORKSHOP</option><option>MEETING</option><option>COMPETITION</option><option>SOCIAL</option><option>OTHER</option></Select></Field><Field label="Venue"><Input required value={form.venue} onChange={(e) => setForm({ ...form, venue: e.target.value })} /></Field><Field label="Status"><Select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option>UPCOMING</option><option>ONGOING</option><option>COMPLETED</option><option>CANCELLED</option></Select></Field></div><div className="grid gap-4 sm:grid-cols-3"><Field label="Start"><Input type="datetime-local" required value={form.startDate} onChange={(e) => setForm({ ...form, startDate: e.target.value })} /></Field><Field label="End"><Input type="datetime-local" required value={form.endDate} onChange={(e) => setForm({ ...form, endDate: e.target.value })} /></Field><Field label="Capacity"><Input type="number" min="1" value={form.maxParticipants} onChange={(e) => setForm({ ...form, maxParticipants: Number(e.target.value) })} /></Field></div>{form.type === "HACKATHON" && <div className="grid gap-4"><Field label="Team formation"><Input value={form.teamFormation} onChange={(e) => setForm({ ...form, teamFormation: e.target.value })} /></Field><Field label="Submission link"><Input value={form.projectSubmission} onChange={(e) => setForm({ ...form, projectSubmission: e.target.value })} /></Field><Field label="Prize details"><Input value={form.prizeDetails} onChange={(e) => setForm({ ...form, prizeDetails: e.target.value })} /></Field></div>}<Button>Save event</Button></form></Modal>;
}
